spring:
  config:
    activate:
      on-profile: mqpurge
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

app:
  feeder:
    mq:
      enabled: true
      queue-name: ${MQ_FEEDER_QUEUE_NAME:H73197_ATP.EXP.02.E}

# ==========================================
# Configuration IBM MQ pour Spring Boot 3
# ==========================================
ibm:
  mq:
    pool:
      enabled: true
    queue-manager: ${IBM_MQ_QUEUE_MANAGER:QM1}
    conn-name: ${IBM_MQ_CONN_NAME:localhost(1414)}
    channel: ${IBM_MQ_CHANNEL:CLIATP01.FRATP01T.T1}
    user: ${IBM_MQ_USER:app}
    password: ${IBM_MQ_PASSWORD:QM1}
    transport-type: ${IBM_MQ_TRANSPORT_TYPE:client}
    ccsid: ${IBM_MQ_CCSID:819}
management:
  health:
    jms:
      enabled: true
