server:
  port: 8085

spring:
  application:
    name: cb-msg-feeder
  jmx:
    enabled: true
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@//localhost:1521/FREEPDB1}
    username: ${DB_USERNAME:ACETP}
    password: ${DB_PASSWORD:Aissa1000*}
    driver-class-name: ${DB_DRIVER:oracle.jdbc.OracleDriver}

ibm:
  mq:
    pool:
      enabled: false

management:
  health:
    jms:
      enabled: false
  endpoints:
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

app:
  feeder:
    poll-interval-ms: ${FEEDER_POLL_INTERVAL_MS:1000}
    max-messages-per-run: ${FEEDER_MAX_MESSAGES_PER_RUN:2000}
    fixed-limit: ${FEEDER_FIXED_LIMIT:true}
    force-specific-branch-enabled: ${FEEDER_FORCE_SPECIFIC_BRANCH_ENABLED:false}
    forced-branch-code: ${FEEDER_FORCED_BRANCH_CODE:DEFF}
    stop-on-max-total-messages-enabled: ${FEEDER_STOP_ON_MAX_TOTAL_MESSAGES_ENABLED:true}
    max-total-messages: ${FEEDER_MAX_TOTAL_MESSAGES:1000000}
    branch-distribution-enabled: ${FEEDER_BRANCH_DISTRIBUTION_ENABLED:true}
    branch-distribution-percentages:
      DEFF: ${FEEDER_BRANCH_PCT_DEFF:30}
      ITMM: ${FEEDER_BRANCH_PCT_ITMM:10}
      PLPX: ${FEEDER_BRANCH_PCT_PLPX:0}
      HUHX: ${FEEDER_BRANCH_PCT_HUHX:0}
      SGSG: ${FEEDER_BRANCH_PCT_SGSG:20}
      HKHH: ${FEEDER_BRANCH_PCT_HKHH:0}
      CHZZ: ${FEEDER_BRANCH_PCT_CHZZ:0}
      AU2S: ${FEEDER_BRANCH_PCT_AU2S:0}
      ESMX: ${FEEDER_BRANCH_PCT_ESMX:20}
      GRAX: ${FEEDER_BRANCH_PCT_GRAX:0}
      GGS1: ${FEEDER_BRANCH_PCT_GGS1:20}
      LULL: ${FEEDER_BRANCH_PCT_LULL:0}
      BEBZ: ${FEEDER_BRANCH_PCT_BEBZ:0}
      JESH: ${FEEDER_BRANCH_PCT_JESH:0}
      GB2L: ${FEEDER_BRANCH_PCT_GB2L:0}
      FRPP: ${FEEDER_BRANCH_PCT_FRPP:0}
    cb-msg-sequence-name: ${FEEDER_CB_MSG_SEQ:ACETP.BDOMO_GRM_TRD_CB_MSGS_DB_ID_Test}
    cl-business-file-sequence-name: ${FEEDER_CL_FILE_SEQ:ACETP.SEQ_CL_BUSINESS_FILE_ID}
    mq:
      enabled: ${MQ_FEEDER_ENABLED:false}
      queue-name: ${MQ_FEEDER_QUEUE_NAME:H73197_ATP.EXP.02.E}
      purge-on-startup-enabled: ${MQ_PURGE_ON_STARTUP_ENABLED:false}
      branch-templates:
        DEFF: ${MQ_TEMPLATE_DEFF:BPF  3050000000MTM     0000069581706958174005RDUSD000000001636346   000000000000000DE260570007829PM2026022620260226                                              DE260570003073TRDEFF                                                                                                                                                                                                                                                                                                                             FRSMP01P            819                 }
        ITMM: ${MQ_TEMPLATE_ITMM:}
        PLPX: ${MQ_TEMPLATE_PLPX:}
        HUHX: ${MQ_TEMPLATE_HUHX:}
        SGSG: ${MQ_TEMPLATE_SGSG:BPF  0000000000MTM     0000081002801081002803RDAUD000000014518636   000000000000000SG260070000720PM2026010720260107                                              SG260070000052TRSGSG                                                                                                                                                                                                                                                                                                                             FRSMP01P            819                 }
        HKHH: ${MQ_TEMPLATE_HKHH:}
        CHZZ: ${MQ_TEMPLATE_CHZZ:}
        AU2S: ${MQ_TEMPLATE_AU2S:}
        ESMX: ${MQ_TEMPLATE_ESMX:}
        GRAX: ${MQ_TEMPLATE_GRAX:}
        GGS1: ${MQ_TEMPLATE_GGS1:}
        LULL: ${MQ_TEMPLATE_LULL:}
        BEBZ: ${MQ_TEMPLATE_BEBZ:}
        JESH: ${MQ_TEMPLATE_JESH:}
        GB2L: ${MQ_TEMPLATE_GB2L:}
        FRPP: ${MQ_TEMPLATE_FRPP:}
