server:
  port: 8082

spring:
  application:
    name: cb-msg-feeder
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@//localhost:1521/FREEPDB1}
    username: ${DB_USERNAME:ACETP}
    password: ${DB_PASSWORD:Aissa1000*}
    driver-class-name: ${DB_DRIVER:oracle.jdbc.OracleDriver}

app:
  feeder:
    poll-interval-ms: ${FEEDER_POLL_INTERVAL_MS:10000}
    max-messages-per-run: ${FEEDER_MAX_MESSAGES_PER_RUN:1000}
    fixed-limit: ${FEEDER_FIXED_LIMIT:true}
    force-specific-branch-enabled: ${FEEDER_FORCE_SPECIFIC_BRANCH_ENABLED:false}
    forced-branch-code: ${FEEDER_FORCED_BRANCH_CODE:}
    stop-on-max-total-messages-enabled: ${FEEDER_STOP_ON_MAX_TOTAL_MESSAGES_ENABLED:false}
    max-total-messages: ${FEEDER_MAX_TOTAL_MESSAGES:100000}
    branch-distribution-enabled: ${FEEDER_BRANCH_DISTRIBUTION_ENABLED:false}
    branch-distribution-percentages:
      DEFF: ${FEEDER_BRANCH_PCT_DEFF:0}
      ITMM: ${FEEDER_BRANCH_PCT_ITMM:100}
      PLPX: ${FEEDER_BRANCH_PCT_PLPX:0}
      HUHX: ${FEEDER_BRANCH_PCT_HUHX:0}
      SGSG: ${FEEDER_BRANCH_PCT_SGSG:0}
      HKHH: ${FEEDER_BRANCH_PCT_HKHH:0}
      CHZZ: ${FEEDER_BRANCH_PCT_CHZZ:0}
      AU2S: ${FEEDER_BRANCH_PCT_AU2S:0}
      ESMX: ${FEEDER_BRANCH_PCT_ESMX:0}
      GRAX: ${FEEDER_BRANCH_PCT_GRAX:0}
      GGS1: ${FEEDER_BRANCH_PCT_GGS1:0}
      LULL: ${FEEDER_BRANCH_PCT_LULL:0}
      BEBZ: ${FEEDER_BRANCH_PCT_BEBZ:0}
      JESH: ${FEEDER_BRANCH_PCT_JESH:0}
      GB2L: ${FEEDER_BRANCH_PCT_GB2L:0}
      FRPP: ${FEEDER_BRANCH_PCT_FRPP:0}
    cb-msg-sequence-name: ${FEEDER_CB_MSG_SEQ:ACETP.BDOMO_GRM_TRD_CB_MSGS_DB_ID_Test}
    cl-business-file-sequence-name: ${FEEDER_CL_FILE_SEQ:ACETP.SEQ_CL_BUSINESS_FILE_ID}
